spring:
  datasource:
    user:
      jdbc-url: jdbc:postgresql://localhost:5433/fitness_tracker_database
      driver-class-name: org.postgresql.Driver
      username: user
      password: qwerty1
    admin:
      jdbc-url: jdbc:postgresql://localhost:5433/fitness_tracker_database
      driver-class-name: org.postgresql.Driver
      username: admin
      password: qwerty2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
